name: NameX Solr Scheduler CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "namex-solr-api/jobs/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - "dev"
          - "test"
          - "sandbox"
          - "prod"
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  namex-solr-sync-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-job-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "namex-solr-sync"
      working_directory: "./namex-solr-api/jobs/namex-solr-sync"
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  namex-solr-heartbeat-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-job-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "namex-solr-heartbeat"
      working_directory: "./namex-solr-api/jobs/namex-solr-heartbeat"
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
